/// <reference path="../pb_data/types.d.ts" />
onRecordCreate((e) => {
  // Generate a simple registration ID if not already set
  // This is a backup in case the system doesn't auto-generate
  if (!e.record.id || e.record.id === "") {
    // PocketBase auto-generates IDs, so this is just a safety check
    console.log("Record ID will be auto-generated by PocketBase");
  }
  e.next();
}, "artisans");